# Generated by Django 5.1.4 on 2025-01-28 16:49

import django.core.validators
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_description_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(default=0, upload_to=games.models.generate_unique_cover_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
