# Generated by Django 5.1.4 on 2025-01-31 03:45

import django.core.validators
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=games.models.generate_unique_cover_image_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
