# Generated by Django 5.1.4 on 2025-01-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_genres', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
