# Generated by Django 5.1.4 on 2025-02-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='twitch_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitch_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status_message',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
