# Generated by Django 5.1.4 on 2025-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0003_remove_customuser_roles_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='games_owned',
        ),
        migrations.AddField(
            model_name='customuser',
            name='owned_games',
            field=models.ManyToManyField(blank=True, related_name='owners', to='games.game'),
        ),
    ]
