# Generated by Django 5.1.4 on 2025-01-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0004_remove_customuser_games_owned_customuser_owned_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_by', to='games.game'),
        ),
    ]
