# Generated by Django 5.1.4 on 2025-01-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_user_game_added_by'),
        ('users', '0007_friendrequest_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='added_games',
            field=models.ManyToManyField(blank=True, related_name='added_games', to='games.game'),
        ),
    ]
